// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VulnerableAPI.Database;

#nullable disable

namespace VulnerableAPI.Migrations.UserDb
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20230930192914_AddData")]
    partial class AddData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("VulnerableAPI.Database.Models.Ledger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Balance")
                        .HasColumnType("REAL");

                    b.Property<int>("Currency")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Iban")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Ledgers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dc63e02a-8375-46c8-811d-0cb2249cbecc"),
                            Balance = 103.0,
                            Currency = 0,
                            Iban = "LT800065400000000428",
                            UserId = new Guid("15a61231-a186-4fc9-ae24-a83d582eaa4d")
                        },
                        new
                        {
                            Id = new Guid("813185ff-1002-45e5-8892-ade558884846"),
                            Balance = 100.0,
                            Currency = 0,
                            Iban = "LT810065400000000216",
                            UserId = new Guid("f373061d-5a04-4725-9140-243236afd26a")
                        },
                        new
                        {
                            Id = new Guid("86e5521e-665f-4ca7-ae1c-846d1d35dfe8"),
                            Balance = 695.0,
                            Currency = 0,
                            Iban = "LT120065400000000391",
                            UserId = new Guid("ff9763ee-b247-48a3-84bd-7099a54a2074")
                        },
                        new
                        {
                            Id = new Guid("b46fe692-341d-4775-bcc5-242826552655"),
                            Balance = 673.0,
                            Currency = 0,
                            Iban = "LT020065400000000571",
                            UserId = new Guid("fd4bd871-01e0-46fc-bbbd-8b0311659f57")
                        },
                        new
                        {
                            Id = new Guid("f4352f51-5ccb-479e-a6c8-2d5f79b6d718"),
                            Balance = 140.0,
                            Currency = 0,
                            Iban = "LT260065400000000915",
                            UserId = new Guid("842b911c-7000-4714-b615-52a8849d569f")
                        },
                        new
                        {
                            Id = new Guid("1cbdc2b6-bf6b-45bc-b10a-ca37791293ea"),
                            Balance = 313.0,
                            Currency = 0,
                            Iban = "LT390065400000000196",
                            UserId = new Guid("a28af4ba-d62c-4a7a-8109-9ff9fac19423")
                        },
                        new
                        {
                            Id = new Guid("74d40f86-6b6a-4fa1-8e46-b274255618e9"),
                            Balance = 664.0,
                            Currency = 0,
                            Iban = "LT100065400000000912",
                            UserId = new Guid("ed807edb-f6bb-4dcf-b293-72d5e4262157")
                        },
                        new
                        {
                            Id = new Guid("cbda0a4c-6420-4379-a6c9-cb31cd2a8f8a"),
                            Balance = 540.0,
                            Currency = 0,
                            Iban = "LT360065400000000444",
                            UserId = new Guid("d3ece0e4-6cb7-4af6-a98b-7bb4169c8b8d")
                        },
                        new
                        {
                            Id = new Guid("0065e6ad-b62b-42b9-aa46-ebd403d70f66"),
                            Balance = 606.0,
                            Currency = 0,
                            Iban = "LT320065400000000904",
                            UserId = new Guid("92b23f71-e891-4616-8e62-f28c761feb25")
                        },
                        new
                        {
                            Id = new Guid("aa4f643e-59d5-4f22-b7d4-893c3855f010"),
                            Balance = 624.0,
                            Currency = 0,
                            Iban = "LT530065400000000623",
                            UserId = new Guid("82f6754f-5d67-4b59-a2c1-936e1d72396d")
                        },
                        new
                        {
                            Id = new Guid("aff85785-faeb-40cf-9169-1c796819cea3"),
                            Balance = 643.0,
                            Currency = 0,
                            Iban = "LT650065400000000892",
                            UserId = new Guid("fc66e5ef-d1e8-4f7d-a845-903f93a90387")
                        },
                        new
                        {
                            Id = new Guid("ac17bc08-8501-4165-bb97-5e77b1d5bbaa"),
                            Balance = 469.0,
                            Currency = 0,
                            Iban = "LT620065400000000267",
                            UserId = new Guid("8adb7e81-d14a-45d7-9b5d-dfc222643029")
                        },
                        new
                        {
                            Id = new Guid("646f7b61-7d2f-4b04-a26b-7c44a5dd84a2"),
                            Balance = 158.0,
                            Currency = 0,
                            Iban = "LT850065400000000338",
                            UserId = new Guid("fcffdaad-83bb-4ba1-83e9-90caeecf147d")
                        },
                        new
                        {
                            Id = new Guid("c4dbca8d-7aa3-475f-bde9-aa81bd7d458f"),
                            Balance = 309.0,
                            Currency = 0,
                            Iban = "LT360065400000000153",
                            UserId = new Guid("133e3479-43b7-484a-8449-0ce31bc82f4c")
                        });
                });

            modelBuilder.Entity("VulnerableAPI.Database.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("15a61231-a186-4fc9-ae24-a83d582eaa4d"),
                            Email = "carmen@marvinhills.name",
                            FirstName = "Rico",
                            IsAdmin = false,
                            LastName = "Runolfsdottir",
                            PasswordHash = "hash",
                            PasswordSalt = "salt"
                        },
                        new
                        {
                            Id = new Guid("f373061d-5a04-4725-9140-243236afd26a"),
                            Email = "marquise@schuster.info",
                            FirstName = "Robb",
                            IsAdmin = false,
                            LastName = "Hermiston",
                            PasswordHash = "hash",
                            PasswordSalt = "salt"
                        },
                        new
                        {
                            Id = new Guid("ff9763ee-b247-48a3-84bd-7099a54a2074"),
                            Email = "phoebe_abernathy@barrows.us",
                            FirstName = "Ruben",
                            IsAdmin = false,
                            LastName = "Yost",
                            PasswordHash = "hash",
                            PasswordSalt = "salt"
                        },
                        new
                        {
                            Id = new Guid("fd4bd871-01e0-46fc-bbbd-8b0311659f57"),
                            Email = "murray_jast@bogan.biz",
                            FirstName = "Jalen",
                            IsAdmin = false,
                            LastName = "Erdman",
                            PasswordHash = "hash",
                            PasswordSalt = "salt"
                        },
                        new
                        {
                            Id = new Guid("842b911c-7000-4714-b615-52a8849d569f"),
                            Email = "rupert_mayert@terryhirthe.co.uk",
                            FirstName = "Mariane",
                            IsAdmin = false,
                            LastName = "Harber",
                            PasswordHash = "hash",
                            PasswordSalt = "salt"
                        },
                        new
                        {
                            Id = new Guid("a28af4ba-d62c-4a7a-8109-9ff9fac19423"),
                            Email = "hilda.kirlin@gleason.ca",
                            FirstName = "Claudie",
                            IsAdmin = false,
                            LastName = "Franecki",
                            PasswordHash = "hash",
                            PasswordSalt = "salt"
                        },
                        new
                        {
                            Id = new Guid("ed807edb-f6bb-4dcf-b293-72d5e4262157"),
                            Email = "curt@powlowski.info",
                            FirstName = "Andreane",
                            IsAdmin = false,
                            LastName = "Gleason",
                            PasswordHash = "hash",
                            PasswordSalt = "salt"
                        },
                        new
                        {
                            Id = new Guid("d3ece0e4-6cb7-4af6-a98b-7bb4169c8b8d"),
                            Email = "bonita@gislasonrosenbaum.ca",
                            FirstName = "Carolina",
                            IsAdmin = false,
                            LastName = "Murray",
                            PasswordHash = "hash",
                            PasswordSalt = "salt"
                        },
                        new
                        {
                            Id = new Guid("92b23f71-e891-4616-8e62-f28c761feb25"),
                            Email = "fletcher_ryan@price.co.uk",
                            FirstName = "Kristofer",
                            IsAdmin = false,
                            LastName = "Schroeder",
                            PasswordHash = "hash",
                            PasswordSalt = "salt"
                        },
                        new
                        {
                            Id = new Guid("82f6754f-5d67-4b59-a2c1-936e1d72396d"),
                            Email = "eugene_damore@monahan.uk",
                            FirstName = "Trent",
                            IsAdmin = false,
                            LastName = "Will",
                            PasswordHash = "hash",
                            PasswordSalt = "salt"
                        },
                        new
                        {
                            Id = new Guid("fc66e5ef-d1e8-4f7d-a845-903f93a90387"),
                            Email = "deontae@pouros.ca",
                            FirstName = "Brooklyn",
                            IsAdmin = false,
                            LastName = "Goyette",
                            PasswordHash = "hash",
                            PasswordSalt = "salt"
                        },
                        new
                        {
                            Id = new Guid("8adb7e81-d14a-45d7-9b5d-dfc222643029"),
                            Email = "shyann@bergnaum.com",
                            FirstName = "Sid",
                            IsAdmin = false,
                            LastName = "Considine",
                            PasswordHash = "hash",
                            PasswordSalt = "salt"
                        },
                        new
                        {
                            Id = new Guid("fcffdaad-83bb-4ba1-83e9-90caeecf147d"),
                            Email = "lauryn.hilll@harveysmith.co.uk",
                            FirstName = "Manuel",
                            IsAdmin = false,
                            LastName = "Leuschke",
                            PasswordHash = "hash",
                            PasswordSalt = "salt"
                        },
                        new
                        {
                            Id = new Guid("133e3479-43b7-484a-8449-0ce31bc82f4c"),
                            Email = "ida@hillswisozk.biz",
                            FirstName = "Brianne",
                            IsAdmin = false,
                            LastName = "Bartell",
                            PasswordHash = "hash",
                            PasswordSalt = "salt"
                        });
                });

            modelBuilder.Entity("VulnerableAPI.Database.Models.Ledger", b =>
                {
                    b.HasOne("VulnerableAPI.Database.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
